"""Desktop/UI schema for the Grad-Shafranov equilibrium module.

The executable solver stays in ``grad_shafranov_equilibrium.py``.  This file
describes how the module appears in the platform: inputs, outputs, defaults,
CLI argument mapping, parameter labels, help text, and interface-file slots.
"""

MODULE_SCHEMA_VERSION = "xirong.module_spec.v1"


MODULE_SPEC = {
    "schema": MODULE_SCHEMA_VERSION,
    "key": "equilibrium_mhd",
    "group": "03 平衡 / MHD / 磁场",
    "title": "03A MHD / Grad-Shafranov 平衡｜磁通与磁场",
    "status": "可运行",
    "script": "modules/equilibrium_mhd/grad_shafranov_equilibrium.py",
    "outdir": "runs/equilibrium_mhd/grad_shafranov",
    "summary": "final_summary.csv",
    "figure": "equilibrium_mhd.png",
    "description": "生成自由/固定边界 Grad-Shafranov 风格平衡，输出磁通、B_R/B_Z/B_phi、总磁场、密度、压强、电流和 q 剖面。",
    "usage": "第 3 步通用平衡入口；输出 equilibrium_state.nc，给 04B full-wave、RF/HCD、后续输运和 PIC 读取。",
    "inputs": {
        "interface_state": {
            "label": "外部/上一轮平衡态 IMAS .nc [路径]",
            "required_in_interface_mode": True,
            "description": "interface 模式读取该 equilibrium_state.nc，用它更新几何、磁场和剖面默认值。",
        },
        "device_machine_state": {
            "label": "01B 装置几何/PF 线圈 IMAS .nc [路径]",
            "required_in_interface_mode": False,
            "default_path": "runs/device_machine/minimal/device_machine_state.nc",
            "description": "manual 或 interface 模式都可选；留空时使用面板里的机器几何和 PF 线圈参数。",
        },
        "machine_config": {
            "label": "机器几何 JSON [可选]",
            "required_in_interface_mode": False,
            "description": "可直接给出 limiter/wall/pf_coils 的真实机器配置；优先级高于 device_machine_state。",
        },
        "geqdsk_input": {
            "label": "EFIT G-EQDSK 平衡文件 [可选]",
            "required_in_interface_mode": False,
            "description": "读取外部 EFIT 风格 g-file 的 R0/a/kappa/B0/Ip/q 与边界轮廓，作为本地求解初始机器模型。",
        },
        "shape_constraint": {
            "label": "形状约束 JSON [可选]",
            "required_in_interface_mode": False,
            "description": "给出 isoflux 点对、X 点或 strike 点目标；shape_control=isoflux 时用于本地 PF 电流最小二乘修正。",
        },
        "diagnostics_constraint": {
            "label": "诊断重建约束 JSON [可选]",
            "required_in_interface_mode": False,
            "description": "给出 flux loop、magnetic probe、q 点和压力点约束，用于本地 weighted reconstruction proxy 和残差诊断。",
        },
        "pressure_profile": {
            "label": "压力剖面 JSON [可选]",
            "required_in_interface_mode": False,
            "description": "给出 rho-pressure 或归一化压力样条点；profile_model=spline 时覆盖 power-law 压力剖面。",
        },
        "current_profile": {
            "label": "电流剖面 JSON [可选]",
            "required_in_interface_mode": False,
            "description": "给出 rho-current/pprime/ffprime 形状点；profile_model=spline 时用于 GS 源项形状。",
        },
        "benchmark_geqdsk": {
            "label": "Benchmark GEQDSK 参考 [可选]",
            "required_in_interface_mode": False,
            "description": "与参考 g-file 的 q 剖面和 LCFS 做轻量误差对比。",
        },
    },
    "outputs": {
        "equilibrium_state": "equilibrium_state.nc",
        "summary": "final_summary.csv",
        "rz_map": "equilibrium_rz_map.csv",
        "q_profile": "q_profile.csv",
        "gs_profiles": "gs_profiles.csv",
        "preview": "equilibrium_mhd.png",
        "diagnostics": "equilibrium_mhd_diagnostics.png",
        "flux_profiles": "equilibrium_flux_profiles.png",
        "source_terms": "equilibrium_gs_source_terms.png",
        "svg_preview": "equilibrium_mhd.svg",
        "model_params": "model_params.csv",
        "imas_manifest": "imas_manifest.json",
        "machine_geometry": "machine_geometry.csv",
        "pf_coils": "pf_coils.csv",
        "passive_structures": "passive_structures.csv",
        "boundary": "equilibrium_boundary.csv",
        "separatrix_topology": "separatrix_topology.csv",
        "x_points": "x_points.csv",
        "strike_points": "strike_points.csv",
        "lcfs_topology_diagnostics": "lcfs_topology_diagnostics.csv",
        "shape_constraints": "shape_constraints.csv",
        "shape_control_response": "shape_control_response.csv",
        "pf_control_matrix": "pf_control_matrix.csv",
        "pf_forward_inverse_summary": "pf_forward_inverse_summary.csv",
        "diagnostic_reconstruction": "diagnostic_reconstruction.csv",
        "diagnostic_reconstruction_by_kind": "diagnostic_reconstruction_by_kind.csv",
        "reconstruction_cost": "reconstruction_cost.csv",
        "reconstruction_parameter_updates": "reconstruction_parameter_updates.csv",
        "benchmark_metrics": "benchmark_metrics.csv",
        "cocos_report": "equilibrium_cocos_report.csv",
        "flux_surface_averages": "flux_surface_averages.csv",
        "chease_profiles": "chease_profiles.csv",
        "chease_summary": "chease_input_summary.json",
        "helena_profiles": "helena_profiles.csv",
        "helena_boundary": "helena_boundary.csv",
        "geqdsk_header": "geqdsk_header.csv",
        "geqdsk_profiles": "geqdsk_profiles.csv",
        "efit_a_file": "equilibrium.afile.csv",
        "efit_k_file": "equilibrium.kfile.csv",
        "efit_m_file": "equilibrium.mfile.csv",
        "export_manifest": "equilibrium_export_manifest.json",
        "geqdsk": "equilibrium.geqdsk",
    },
    "interface_files": ("interface_state", "device_machine_state", "machine_config", "geqdsk_input", "shape_constraint", "diagnostics_constraint", "pressure_profile", "current_profile", "benchmark_geqdsk"),
    "required_interface_files": ("interface_state",),
    "interface_mode_visible_params": ("input_mode", "interface_state", "device_machine_state", "machine_config", "geqdsk_input", "shape_constraint", "diagnostics_constraint", "pressure_profile", "current_profile", "benchmark_geqdsk"),
    "upstream_files": {
        "device_machine_state": (
            "runs/device_machine/minimal/device_machine_state.nc",
            "先运行第 1 步“01B 装置几何 / PF 线圈｜机器边界”",
        ),
        "interface_state": (
            "runs/equilibrium_mhd/grad_shafranov/equilibrium_state.nc",
            "可选择外部 IMAS 平衡态，或上一轮 03A 生成的 equilibrium_state.nc",
        ),
    },
    "defaults": {
        "input_mode": "manual",
        "interface_state": "",
        "device_machine_state": "",
        "machine_config": "",
        "geqdsk_input": "",
        "geqdsk_output": "equilibrium.geqdsk",
        "shape_constraint": "",
        "diagnostics_constraint": "",
        "reconstruction_mode": "off",
        "reconstruction_gain": "0.5",
        "reconstruction_fit_params": "b0_t,plasma_current_ma,beta_percent,q_axis,q_edge,poloidal_field_fraction",
        "reconstruction_regularization": "1e-2",
        "profile_model": "power-law",
        "pressure_profile": "",
        "current_profile": "",
        "benchmark_geqdsk": "",
        "cocos_index": "11",
        "psi_sign": "1.0",
        "ip_sign": "1.0",
        "btor_sign": "1.0",
        "export_formats": "profiles,chease,helena,efit",
        "shape_control": "off",
        "shape_control_gain": "0.65",
        "shape_control_current_limit_ma": "2.0",
        "shape_control_damping": "1e-5",
        "equilibrium_model": "free-boundary-gs",
        "n_r": "72",
        "n_z": "96",
        "major_radius_m": "1.85",
        "minor_radius_m": "0.55",
        "elongation": "1.65",
        "triangularity": "0.18",
        "b0_t": "3.0",
        "plasma_current_ma": "0.75",
        "beta_percent": "2.2",
        "q_axis": "1.05",
        "q_edge": "4.0",
        "pressure_alpha": "1.6",
        "current_alpha": "1.2",
        "pressure_current_fraction": "0.55",
        "density_axis_1e19_m3": "1.0",
        "density_edge_fraction": "0.22",
        "temperature_axis_kev": "8.0",
        "poloidal_field_fraction": "0.08",
        "gs_iterations": "1500",
        "gs_relaxation": "1.15",
        "gs_tolerance": "1e-3",
        "free_boundary_extent": "1.45",
        "boundary_update_every": "50",
        "boundary_relaxation": "0.03",
        "pf_coil_current_ma": "0.0",
        "pf_coil_r_offset_m": "0.72",
        "pf_coil_z_m": "1.08",
        "pf_coil_turns": "1.0",
        "limiter_points": "192",
        "wall_clearance_m": "0.08",
    },
    "args": (
        ("--input-mode", "input_mode"),
        ("--interface-state", "interface_state"),
        ("--device-machine-state", "device_machine_state"),
        ("--machine-config", "machine_config"),
        ("--geqdsk-input", "geqdsk_input"),
        ("--geqdsk-output", "geqdsk_output"),
        ("--shape-constraint", "shape_constraint"),
        ("--diagnostics-constraint", "diagnostics_constraint"),
        ("--reconstruction-mode", "reconstruction_mode"),
        ("--reconstruction-gain", "reconstruction_gain"),
        ("--reconstruction-fit-params", "reconstruction_fit_params"),
        ("--reconstruction-regularization", "reconstruction_regularization"),
        ("--profile-model", "profile_model"),
        ("--pressure-profile", "pressure_profile"),
        ("--current-profile", "current_profile"),
        ("--benchmark-geqdsk", "benchmark_geqdsk"),
        ("--cocos-index", "cocos_index"),
        ("--psi-sign", "psi_sign"),
        ("--ip-sign", "ip_sign"),
        ("--btor-sign", "btor_sign"),
        ("--export-formats", "export_formats"),
        ("--shape-control", "shape_control"),
        ("--shape-control-gain", "shape_control_gain"),
        ("--shape-control-current-limit-ma", "shape_control_current_limit_ma"),
        ("--shape-control-damping", "shape_control_damping"),
        ("--equilibrium-model", "equilibrium_model"),
        ("--n-r", "n_r"),
        ("--n-z", "n_z"),
        ("--major-radius-m", "major_radius_m"),
        ("--minor-radius-m", "minor_radius_m"),
        ("--elongation", "elongation"),
        ("--triangularity", "triangularity"),
        ("--b0-t", "b0_t"),
        ("--plasma-current-ma", "plasma_current_ma"),
        ("--beta-percent", "beta_percent"),
        ("--q-axis", "q_axis"),
        ("--q-edge", "q_edge"),
        ("--pressure-alpha", "pressure_alpha"),
        ("--current-alpha", "current_alpha"),
        ("--pressure-current-fraction", "pressure_current_fraction"),
        ("--density-axis-1e19-m3", "density_axis_1e19_m3"),
        ("--density-edge-fraction", "density_edge_fraction"),
        ("--temperature-axis-kev", "temperature_axis_kev"),
        ("--poloidal-field-fraction", "poloidal_field_fraction"),
        ("--gs-iterations", "gs_iterations"),
        ("--gs-relaxation", "gs_relaxation"),
        ("--gs-tolerance", "gs_tolerance"),
        ("--free-boundary-extent", "free_boundary_extent"),
        ("--boundary-update-every", "boundary_update_every"),
        ("--boundary-relaxation", "boundary_relaxation"),
        ("--pf-coil-current-ma", "pf_coil_current_ma"),
        ("--pf-coil-r-offset-m", "pf_coil_r_offset_m"),
        ("--pf-coil-z-m", "pf_coil_z_m"),
        ("--pf-coil-turns", "pf_coil_turns"),
        ("--limiter-points", "limiter_points"),
        ("--wall-clearance-m", "wall_clearance_m"),
    ),
    "param_choices": {
        "input_mode": ("manual", "interface"),
        "equilibrium_model": ("free-boundary-gs", "iterative-gs", "elongated-tokamak", "circular-tokamak", "solovev"),
        "shape_control": ("off", "forward", "isoflux", "inverse", "forward-inverse"),
        "reconstruction_mode": ("off", "weighted", "least-squares"),
        "profile_model": ("power-law", "spline"),
        "psi_sign": ("1.0", "-1.0"),
        "ip_sign": ("1.0", "-1.0"),
        "btor_sign": ("1.0", "-1.0"),
    },
    "param_labels": {
        "input_mode": "输入方式",
        "interface_state": "外部/上一轮平衡态 IMAS .nc [路径]",
        "device_machine_state": "01B 装置几何/PF 线圈 IMAS .nc [路径]",
        "machine_config": "机器几何 JSON [可选]",
        "geqdsk_input": "EFIT G-EQDSK 输入 [可选]",
        "geqdsk_output": "G-EQDSK 输出文件名",
        "shape_constraint": "形状约束 JSON [可选]",
        "diagnostics_constraint": "诊断重建约束 JSON [可选]",
        "reconstruction_mode": "诊断重建模式",
        "reconstruction_gain": "重建参数更新增益",
        "reconstruction_fit_params": "重建拟合参数列表",
        "reconstruction_regularization": "重建最小二乘正则",
        "profile_model": "剖面模型",
        "pressure_profile": "压力剖面 JSON [可选]",
        "current_profile": "电流剖面 JSON [可选]",
        "benchmark_geqdsk": "Benchmark GEQDSK 参考 [可选]",
        "cocos_index": "COCOS 约定编号",
        "psi_sign": "psi 符号",
        "ip_sign": "Ip 符号",
        "btor_sign": "Btor 符号",
        "export_formats": "导出格式列表",
        "shape_control": "PF 形状控制",
        "shape_control_gain": "PF 修正增益",
        "shape_control_current_limit_ma": "PF 控制电流限幅 [MA]",
        "shape_control_damping": "PF 最小二乘阻尼",
        "equilibrium_model": "平衡模型",
        "n_r": "径向网格数",
        "n_z": "垂向网格数",
        "major_radius_m": "主半径 R0 [m]",
        "minor_radius_m": "小半径 a [m]",
        "elongation": "拉长比 kappa",
        "triangularity": "三角形变 delta",
        "b0_t": "轴向磁场 B0 [T]",
        "plasma_current_ma": "等离子体电流 [MA]",
        "beta_percent": "Beta [%]",
        "q_axis": "轴上安全因子 q0",
        "q_edge": "边界安全因子 qa",
        "pressure_alpha": "压强剖面指数",
        "current_alpha": "电流剖面指数",
        "pressure_current_fraction": "pprime 电流份额 beta0",
        "density_axis_1e19_m3": "轴上密度 [1e19 m^-3]",
        "density_edge_fraction": "边缘密度份额",
        "temperature_axis_kev": "轴上温度 [keV]",
        "poloidal_field_fraction": "极向场比例",
        "gs_iterations": "GS 迭代上限 [步]",
        "gs_relaxation": "GS 松弛因子",
        "gs_tolerance": "GS 收敛阈值",
        "free_boundary_extent": "自由边界计算盒尺寸 [a]",
        "boundary_update_every": "边界磁通更新间隔 [步]",
        "boundary_relaxation": "边界磁通松弛因子",
        "pf_coil_current_ma": "PF 线圈电流 [MA]",
        "pf_coil_r_offset_m": "PF 线圈小半径位置 [m]",
        "pf_coil_z_m": "PF 线圈高度 [m]",
        "pf_coil_turns": "PF 线圈匝数",
        "limiter_points": "默认 limiter 点数",
        "wall_clearance_m": "默认壁面裕量 [m]",
    },
    "param_help": {
        "input_mode": "manual=用本面板参数生成新平衡；interface=读取外部/上一轮 equilibrium_state.nc 更新默认几何和剖面。",
        "interface_state": "外部或上一轮 03A 平衡态；interface 模式必填。",
        "device_machine_state": "01B 装置几何/PF 线圈状态；可选。留空时使用本面板的几何和 PF 线圈参数。",
        "machine_config": "JSON 格式机器配置，支持 limiter/wall 的 r_m/z_m 数组和 pf_coils 列表；填写后优先使用该文件。",
        "geqdsk_input": "本地解析 EFIT G-EQDSK/g-file，读取 R/Z 网格、LCFS、limiter、q 剖面和 Ip/B0 标量；不调用外部 FreeGS/EFIT 后端。",
        "geqdsk_output": "运行完成后写出的 EFIT 风格 G-EQDSK 文件；相对路径会写到输出目录。",
        "shape_constraint": "JSON 支持 isoflux 点对 r1_m/z1_m/r2_m/z2_m，以及 xpoints/strike_points/points 的 r_m/z_m/weight。",
        "diagnostics_constraint": "JSON 支持 flux_loops、magnetic_probes、q_points、pressure_points、mse_points、rogowski_current、diamagnetic_loop 和 lcfs_points；程序会写 diagnostic_reconstruction.csv、按类型汇总和 summary 残差。",
        "reconstruction_mode": "off=只报告残差；weighted=按诊断目标做标量混合更新；least-squares=构造 EFIT-like 线性化 cost/Jacobian，解加权最小二乘参数更新并写 reconstruction_cost.csv。",
        "reconstruction_gain": "诊断目标对输入参数更新的混合比例；least-squares 模式下用于限制本轮线性步长。",
        "reconstruction_fit_params": "least-squares 模式拟合的逗号分隔参数，支持 b0_t、plasma_current_ma、beta_percent、q_axis、q_edge、poloidal_field_fraction、pressure_current_fraction。",
        "reconstruction_regularization": "least-squares 模式的 Tikhonov 正则；约束少或灵敏度矩阵接近奇异时增大。",
        "profile_model": "power-law=使用默认解析剖面；spline=读取 pressure_profile/current_profile 的 rho 样条点。",
        "pressure_profile": "JSON 可含 rho 与 pressure_pa 或 pressure_norm；用于压力剖面和 pprime 源项。",
        "current_profile": "JSON 可含 rho 与 current_norm/j_norm/pprime_norm/ffprime_norm；用于电流源项形状。",
        "benchmark_geqdsk": "参考 EFIT/FreeGS g-file；输出 benchmark_metrics.csv，比较 q profile 和 LCFS 距离。",
        "cocos_index": "本地导出用的 COCOS-like 标记；目前记录和报告符号约定，不做外部库转换。",
        "psi_sign": "导出报告中的 poloidal flux 符号元数据。",
        "ip_sign": "导出报告中的 plasma current 符号元数据。",
        "btor_sign": "导出报告中的 toroidal field 符号元数据。",
        "export_formats": "逗号分隔：profiles,chease,helena,efit,imas；写 flux_surface_averages、增强 CHEASE/HELENA 桥接 CSV 和 EFIT-like a/k/m sidecar。",
        "shape_control": "off=不修正 PF 电流；forward=只报告给定线圈电流产生的形状残差；isoflux/inverse=给定形状反求 PF 电流；forward-inverse=同时输出 forward 残差和 inverse 响应矩阵。",
        "shape_control_gain": "把最小二乘求得的 PF 电流增量按该比例施加，默认 0.65 以避免一次修正过冲。",
        "shape_control_current_limit_ma": "每个可控 PF 线圈最终电流的绝对值限幅。",
        "shape_control_damping": "线圈响应矩阵的 Tikhonov 阻尼；约束点少或线圈响应接近奇异时增大。",
        "equilibrium_model": "free-boundary-gs=自由边界迭代；iterative-gs=固定边界迭代；elongated/circular/solovev=解析对照。",
        "gs_iterations": "最大 GS/SOR 迭代次数；网格更细或边界更新更慢时可提高。",
        "gs_relaxation": "SOR 松弛因子。默认 1.15 对自由边界较稳。",
        "gs_tolerance": "相邻迭代磁通变化的归一化收敛阈值。",
        "pressure_current_fraction": "控制 J_phi 中 R*pprime 压强梯度电流的份额，其余由 ffprime/(mu0 R) 承担。",
        "free_boundary_extent": "自由边界计算盒半宽，单位为小半径 a；需要覆盖等离子体外真空区。",
        "boundary_update_every": "自由边界模式每隔多少步用当前电流分布重算外边界真空磁通。",
        "boundary_relaxation": "外边界磁通更新权重；默认较小，优先保证稳定收敛。shape_control 打开时求解器会把有效值上限降到 0.005，抑制 PF 修正后的边界振荡。",
        "pf_coil_current_ma": "简化上下 PF 线圈对电流；0 表示关闭外加整形场代理。",
        "pf_coil_r_offset_m": "PF 线圈相对磁轴的小半径位置。",
        "pf_coil_z_m": "上下对称 PF 线圈高度。",
        "pf_coil_turns": "默认参数化 PF 线圈匝数；读取真实机器配置时可由文件覆盖。",
        "limiter_points": "没有外部机器边界时生成 D 形 limiter 的离散点数。",
        "wall_clearance_m": "没有外部壁面时在 limiter 外扩生成 wall 的径向裕量。",
    },
}
